#!/bin/bash

echo "Build hook running"

BUILD_VERSION=`curl --silent --head https://www.sheepit-renderfarm.com/media/applet/client-latest.php | grep -Po 'filename="sheepit-client-\K([^"])+(?=.jar)'`

docker build \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
    --build-arg BUILD_VERSION=$BUILD_VERSION
    --tag $IMAGE_NAME:$BUILD_VERSION .
