#!/bin/bash

DOCKER_TAG=`curl --silent --head https://www.sheepit-renderfarm.com/media/applet/client-latest.php | grep -Po 'filename="sheepit-client-\K([^"])+(?=.jar)'`

docker tag $IMAGE_NAME $DOCKER_REPO:$DOCKER_TAG
docker push $DOCKER_REPO:$DOCKER_TAG
